import * as THREE from '../vendor/three.module.min.js';
import {CARD_CATALOG,DECK_SIZE,validateDecks} from './core.js?v=1.6.0';
import {effectivePresets,initialDecks} from './deck-builder.js?v=1.6.0';

const STORAGE_KEY='ge_vr_deck_selection',catalog=[...CARD_CATALOG],FILTERS=[{label:'TODAS',accept:()=>true},...Array.from({length:7},(_,cost)=>({label:`CUSTO ${cost}`,accept:card=>card.cost===cost}))];
function box(parent,x,y,z,w,h,d,color){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.9,metalness:0}));mesh.position.set(x,y,z);parent.add(mesh);return mesh;}
function textPanel(parent,id,w,h,{pixelsX=512,pixelsY=256}={}){
 const canvas=document.createElement('canvas');canvas.width=pixelsX;canvas.height=pixelsY;const ctx=canvas.getContext('2d'),texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;
 const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:texture,transparent:true,side:THREE.DoubleSide}));mesh.userData={kind:'deck-room',id};parent.add(mesh);return {mesh,canvas,ctx,texture};
}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath();}
function fit(ctx,text,maxWidth,start=34,min=15){let size=start;while(size>min){ctx.font=`bold ${size}px sans-serif`;if(ctx.measureText(text).width<=maxWidth)break;size--;}return size;}
function shuffle(items){const out=items.slice();for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}

export function createDeckRoom(scene,{onStart,storage=globalThis.localStorage}={}){
 const stage=new THREE.Group();scene.add(stage);const controls=[];
 const shell=new THREE.Mesh(new THREE.ConeGeometry(7.2,5.5,4,1,true),new THREE.MeshStandardMaterial({color:0x40301f,side:THREE.BackSide,roughness:1}));shell.position.set(0,2.65,-2.2);shell.rotation.y=Math.PI/4;stage.add(shell);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(12,12),new THREE.MeshStandardMaterial({color:0x5c4932,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.set(0,-.015,-2);stage.add(floor);
 box(stage,0,1.7,-4.6,6.3,3.4,.24,0x493721);box(stage,-3.25,1.25,-2.8,.42,2.5,.42,0x765a34);box(stage,3.25,1.25,-2.8,.42,2.5,.42,0x765a34);
 for(const x of [-2.7,2.7]){box(stage,x,.9,-3.9,.34,1.8,.34,0x8a693d);const flame=new THREE.Mesh(new THREE.ConeGeometry(.075,.24,8),new THREE.MeshBasicMaterial({color:0xffb13b}));flame.position.set(x,1.95,-3.83);stage.add(flame);const light=new THREE.PointLight(0xffb45c,1.7,5);light.position.copy(flame.position);stage.add(light);}
 box(stage,0,.56,-1.42,3.65,.18,1.72,0x77634a);box(stage,-1.45,.27,-1.42,.38,.55,1.25,0x594631);box(stage,1.45,.27,-1.42,.38,.55,1.25,0x594631);
 const ui=new THREE.Group();ui.position.set(0,1.72,-2.05);stage.add(ui);box(ui,0,0,-.045,3.42,2.5,.09,0x5b4a36);
 const title=textPanel(ui,'none',3.18,.31,{pixelsX:1024,pixelsY:160});title.mesh.position.set(0,1.05,.015);title.mesh.raycast=()=>{};
 const sideButtons=[textPanel(ui,'side-0',1.45,.22),textPanel(ui,'side-1',1.45,.22)];sideButtons[0].mesh.position.set(-.78,.78,.02);sideButtons[1].mesh.position.set(.78,.78,.02);
 const scrollSurface=new THREE.Mesh(new THREE.PlaneGeometry(3.2,1.2),new THREE.MeshBasicMaterial({transparent:true,opacity:0,side:THREE.DoubleSide,depthWrite:false}));scrollSurface.position.set(0,-.14,.012);scrollSurface.userData={kind:'deck-room',id:'scroll-area'};ui.add(scrollSurface);
 const cards=Array.from({length:16},(_,i)=>{const p=textPanel(ui,'card-'+i,.35,.49,{pixelsX:384,pixelsY:512});p.mesh.position.set(-1.47+(i%8)*.42,.28-Math.floor(i/8)*.54,.025);return p;});
 const previous=textPanel(ui,'previous',.34,.18),pageLabel=textPanel(ui,'none',.42,.18),next=textPanel(ui,'next',.34,.18);previous.mesh.position.set(-.4,-.73,.02);pageLabel.mesh.position.set(0,-.73,.02);pageLabel.mesh.raycast=()=>{};next.mesh.position.set(.4,-.73,.02);
 const filterButtons=FILTERS.map((_,i)=>{const p=textPanel(stage,'filter-'+i,.39,.2,{pixelsX:512,pixelsY:192});p.mesh.position.set(-1.47+i*.42,.675,-1.43);p.mesh.rotation.x=-Math.PI/2;return p;});
 const presetEntries=Object.entries(effectivePresets(storage?.getItem?.('ge_preset_overrides')));
 const presetButtons=presetEntries.map((_,i)=>{const p=textPanel(stage,'preset-'+i,.39,.2,{pixelsX:512,pixelsY:192});p.mesh.position.set(-1.47+i*.42,.675,-1.16);p.mesh.rotation.x=-Math.PI/2;return p;});
 const random=textPanel(stage,'random',.78,.2),clear=textPanel(stage,'clear',.66,.2);random.mesh.position.set(-.46,.675,-.88);clear.mesh.position.set(.46,.675,-.88);random.mesh.rotation.x=clear.mesh.rotation.x=-Math.PI/2;
 const start=textPanel(stage,'start',1.62,.32,{pixelsX:1024,pixelsY:220});start.mesh.position.set(0,.68,-.64);start.mesh.rotation.x=-Math.PI/2;
 const detail=new THREE.Group();detail.position.set(0,2.25,-1.05);stage.add(detail);detail.visible=false;
 const detailHit=new THREE.Mesh(new THREE.PlaneGeometry(1.02,1.16),new THREE.MeshBasicMaterial({transparent:true,opacity:0,side:THREE.DoubleSide,depthTest:false,depthWrite:false}));detailHit.userData={kind:'deck-room',id:'detail-close'};detailHit.renderOrder=190;detail.add(detailHit);
 const detailCard=textPanel(detail,'none',.96,.86,{pixelsX:1024,pixelsY:1024});detailCard.mesh.position.y=.13;detailCard.mesh.raycast=()=>{};detailCard.mesh.material.depthTest=false;detailCard.mesh.renderOrder=200;
 const detailAdd=textPanel(detail,'detail-add',.44,.19),detailRemove=textPanel(detail,'detail-remove',.44,.19);detailAdd.mesh.position.set(-.25,-.43,.025);detailRemove.mesh.position.set(.25,-.43,.025);for(const panel of [detailAdd,detailRemove]){panel.mesh.material.depthTest=false;panel.mesh.renderOrder=210;}
 controls.push(...sideButtons.map(p=>p.mesh),scrollSurface,...cards.map(p=>p.mesh),previous.mesh,next.mesh,...filterButtons.map(p=>p.mesh),...presetButtons.map(p=>p.mesh),random.mesh,clear.mesh,start.mesh,detailHit,detailAdd.mesh,detailRemove.mesh);
 const artImages=new Map();
 let decks=initialDecks(storage?.getItem?.(STORAGE_KEY)),side=0,row=0,filterIndex=0,detailKey=null,drag=null,message='Use os filtros na mesa. Clique em uma carta para examiná-la.';
 function persist(){try{storage?.setItem?.(STORAGE_KEY,JSON.stringify({v:1,decks}));}catch{}}
 function paintButton(panel,label,{active=false,enabled=true,accent='#d7b56d',small=false,fontSize=null}={}){const {ctx,canvas,texture}=panel;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle=enabled?(active?'#2d625d':'#1a2c32'):'#242321';roundRect(ctx,4,4,canvas.width-8,canvas.height-8,18);ctx.fill();ctx.strokeStyle=active?'#8dfff2':enabled?accent:'#554f46';ctx.lineWidth=active?13:7;ctx.stroke();ctx.fillStyle=enabled?'#fff0c5':'#777168';ctx.textAlign='center';ctx.textBaseline='middle';fit(ctx,label,canvas.width-28,fontSize??(small?25:31),fontSize?Math.min(50,fontSize):14);ctx.fillText(label,canvas.width/2,canvas.height/2,canvas.width-24);texture.needsUpdate=true;panel.mesh.visible=!!label;panel.mesh.userData.fontSize=fontSize??(small?25:31);panel.mesh.userData.active=active;panel.mesh.userData.enabled=enabled;}
 function ensureArt(card){if(typeof Image==='undefined'||artImages.has(card.key))return artImages.get(card.key);const image=new Image();artImages.set(card.key,image);image.onload=render;image.onerror=()=>{image.failed=true;render();};image.src=new URL(`../card-art/${card.art}.webp`,import.meta.url).href;return image;}
 function paintCard(panel,card,index){const {ctx,canvas,texture}=panel;ctx.clearRect(0,0,canvas.width,canvas.height);if(!card){panel.mesh.visible=false;panel.mesh.userData.cardKey=null;return;}panel.mesh.visible=true;const selected=decks[side].includes(card.key),image=ensureArt(card);ctx.fillStyle=selected?'#273f3b':'#112631';roundRect(ctx,4,4,canvas.width-8,canvas.height-8,18);ctx.fill();ctx.save?.();roundRect(ctx,13,13,canvas.width-26,300,12);ctx.clip?.();if(image?.complete&&!image.failed&&image.naturalWidth){const scale=Math.max((canvas.width-26)/image.naturalWidth,300/image.naturalHeight),w=image.naturalWidth*scale,h=image.naturalHeight*scale;ctx.drawImage(image,13+(canvas.width-26-w)/2,13+(300-h)/2,w,h);}else{ctx.fillStyle='#243d45';ctx.fillRect(13,13,canvas.width-26,300);ctx.fillStyle='#d5ba7a';ctx.font='bold 104px Georgia';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('☥',canvas.width/2,162);}ctx.restore?.();ctx.fillStyle='rgba(7,17,23,.94)';ctx.fillRect(13,310,canvas.width-26,189);ctx.strokeStyle=selected?'#71eee2':'#b99a5d';ctx.lineWidth=selected?10:6;roundRect(ctx,4,4,canvas.width-8,canvas.height-8,18);ctx.stroke();ctx.textAlign='left';ctx.textBaseline='middle';ctx.fillStyle='#fff0c5';fit(ctx,card.name,canvas.width-82,31,16);ctx.fillText(card.name,19,349,canvas.width-80);ctx.fillStyle='#7ee5ed';ctx.font='bold 23px sans-serif';ctx.fillText(`${card.cost} EN · ${card.power} POD`,19,391);ctx.fillStyle='#c9c5ba';ctx.font='19px sans-serif';ctx.fillText(card.type,19,430,canvas.width-38);ctx.fillStyle=selected?'#71eee2':'#d5ba7a';ctx.font='bold 39px sans-serif';ctx.textAlign='center';ctx.fillText(selected?String(decks[side].indexOf(card.key)+1):'＋',canvas.width-38,350);texture.needsUpdate=true;panel.mesh.userData.cardIndex=index;panel.mesh.userData.cardKey=card.key;}
 function paintDetail(card){const {ctx,canvas,texture}=detailCard,image=ensureArt(card);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#091923f7';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#d8b46d';ctx.lineWidth=13;ctx.strokeRect(8,8,canvas.width-16,canvas.height-16);ctx.fillStyle='#203b43';ctx.fillRect(35,35,410,720);if(image?.complete&&!image.failed&&image.naturalWidth){const scale=Math.max(410/image.naturalWidth,720/image.naturalHeight),w=image.naturalWidth*scale,h=image.naturalHeight*scale;ctx.drawImage(image,35+(410-w)/2,35+(720-h)/2,w,h);}else{ctx.fillStyle='#d5ba7a';ctx.font='bold 180px Georgia';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('☥',240,395);}ctx.textAlign='left';ctx.textBaseline='alphabetic';ctx.fillStyle='#fff0c5';fit(ctx,card.name,510,62,34);ctx.fillText(card.name,480,92,510);ctx.fillStyle='#72e5ed';ctx.font='bold 39px sans-serif';ctx.fillText(`${card.cost} ENERGIA · ${card.power} PODER`,480,155,510);ctx.fillStyle='#d8b46d';ctx.font='bold 32px sans-serif';ctx.fillText(card.type.toUpperCase(),480,211,510);ctx.fillStyle='#edf4ee';ctx.font='31px sans-serif';let line='',y=278,lines=0;for(const word of card.text.split(' ')){const next=line+word+' ';if(ctx.measureText(next).width>500){ctx.fillText(line,480,y);y+=42;lines++;line=word+' ';}else line=next;if(lines>=11)break;}if(lines<11)ctx.fillText(line,480,y);ctx.fillStyle=decks[side].includes(card.key)?'#72e5ed':'#c9c5ba';ctx.font='bold 28px sans-serif';ctx.fillText(decks[side].includes(card.key)?`NO DECK · POSIÇÃO ${decks[side].indexOf(card.key)+1}`:'FORA DO DECK',480,790);texture.needsUpdate=true;}
 function filteredCards(){return catalog.filter(FILTERS[filterIndex].accept);}
 function render(){
  const visibleCatalog=filteredCards(),maxRow=Math.max(0,Math.ceil(visibleCatalog.length/8)-2);row=Math.min(row,maxRow);const active=side===0?'SEU DECK':'DECK DO BOT';
  const {ctx,canvas,texture}=title;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#17242a';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#a98951';ctx.lineWidth=7;ctx.strokeRect(4,4,canvas.width-8,canvas.height-8);ctx.textAlign='center';ctx.fillStyle='#f6dda6';ctx.font='bold 39px Georgia';ctx.fillText('CÂMARA DOS DECKS',canvas.width/2,51);ctx.fillStyle='#78e1e8';ctx.font='bold 25px sans-serif';ctx.fillText(`${active} · ${decks[side].length}/${DECK_SIZE}`,canvas.width/2,91);ctx.fillStyle='#d4c7ad';ctx.font='20px sans-serif';ctx.fillText(message,canvas.width/2,128,canvas.width-34);texture.needsUpdate=true;
  paintButton(sideButtons[0],`SEU DECK · ${decks[0].length}/12`,{active:side===0});paintButton(sideButtons[1],`DECK DO BOT · ${decks[1].length}/12`,{active:side===1,accent:'#7dd3fc'});
  const offset=row*8;cards.forEach((panel,i)=>paintCard(panel,visibleCatalog[offset+i],offset+i));paintButton(previous,'▲',{enabled:row>0});paintButton(next,'▼',{enabled:row<maxRow});paintButton(pageLabel,`${row+1} / ${maxRow+1}`,{small:true});
  filterButtons.forEach((button,i)=>paintButton(button,FILTERS[i].label,{active:i===filterIndex,fontSize:56}));presetButtons.forEach((button,i)=>{const [name,cards]=presetEntries[i],active=decks[side].length===cards.length&&decks[side].every((key,index)=>key===cards[index]);paintButton(button,name.toUpperCase(),{active,fontSize:56,accent:'#d8b46d'});});
  paintButton(random,'ALEATÓRIO',{fontSize:46});paintButton(clear,'LIMPAR',{fontSize:46});paintButton(start,'INICIAR PARTIDA',{active:validateDecks(decks).ok,enabled:validateDecks(decks).ok});
  const detailVisible=!!detailKey;detail.visible=detailVisible;detailHit.visible=detailAdd.mesh.visible=detailRemove.mesh.visible=detailVisible;if(detailKey){const card=catalog.find(item=>item.key===detailKey);paintDetail(card);const selected=decks[side].includes(card.key);paintButton(detailAdd,'ADICIONAR',{active:!selected,enabled:!selected&&decks[side].length<DECK_SIZE});paintButton(detailRemove,'RETIRAR',{active:selected,enabled:selected,accent:'#f29a83'});}
 }
 function activate(id,object){
  if(id==='side-0'||id==='side-1'){side=Number(id.at(-1));message=side?'Agora escolha o deck do guardião.':'Agora escolha o seu deck.';render();return;}
  if(id.startsWith('filter-')){filterIndex=Number(id.slice(7));row=0;detailKey=null;message=`Filtro ${FILTERS[filterIndex].label}.`;render();return;}
  if(id.startsWith('preset-')){const preset=presetEntries[Number(id.slice(7))];if(preset){decks[side]=preset[1].slice();detailKey=null;message=`Preset ${preset[0]} carregado.`;persist();render();}return;}
  if(id==='previous'){navigate(-1);return;}if(id==='next'){navigate(1);return;}
  if(id.startsWith('card-')){const card=catalog.find(item=>item.key===object.userData.cardKey);if(!card)return;detailKey=card.key;message=`Examinando ${card.name}.`;render();return;}
  if(id==='detail-close'){detailKey=null;render();return;}
  if(id==='detail-add'){const card=catalog.find(item=>item.key===detailKey);if(!card||decks[side].includes(card.key))return;if(decks[side].length>=DECK_SIZE){message='Deck completo. Retire uma carta primeiro.';render();return;}decks[side].push(card.key);message=`${card.name} adicionada.`;persist();render();return;}
  if(id==='detail-remove'){const card=catalog.find(item=>item.key===detailKey),index=decks[side].indexOf(card?.key);if(index<0)return;decks[side].splice(index,1);message=`${card.name} retirada.`;persist();render();return;}
  if(id==='random'){decks[side]=shuffle(catalog).slice(0,DECK_SIZE).map(card=>card.key);message='Deck aleatório montado.';persist();render();return;}
  if(id==='clear'){decks[side]=[];message='Deck limpo.';persist();render();return;}
  if(id==='start'){const valid=validateDecks(decks);if(!valid.ok){message=valid.reason;render();return;}persist();const result=onStart?.(decks.map(deck=>deck.slice()));if(result?.ok===false){message=result.reason;render();return;}stage.visible=false;}
 }
 function navigate(delta){const maxRow=Math.max(0,Math.ceil(filteredCards().length/8)-2),next=Math.max(0,Math.min(maxRow,row+Math.sign(delta)));if(next===row)return false;row=next;message=`Coleção · posição ${row+1} de ${maxRow+1}.`;render();return true;}
 const dragPlane=new THREE.Plane(),dragNormal=new THREE.Vector3(),dragOrigin=new THREE.Vector3(),dragPoint=new THREE.Vector3(),dragQuaternion=new THREE.Quaternion();
 function pointerStart(source,hit){if(!hit)return false;const {id}=hit.object.userData;if(id==='scroll-area'||id?.startsWith('card-')){const local=ui.worldToLocal(hit.point.clone());drag={source,id,object:hit.object,startY:local.y,startRow:row,moved:false};return true;}activate(id,hit.object);return true;}
 function pointerMove(source,ray){if(!drag||drag.source!==source)return false;ui.updateWorldMatrix(true,false);ui.getWorldPosition(dragOrigin);ui.getWorldQuaternion(dragQuaternion);dragNormal.set(0,0,1).applyQuaternion(dragQuaternion);dragPlane.setFromNormalAndCoplanarPoint(dragNormal,dragOrigin);if(!ray.intersectPlane(dragPlane,dragPoint))return false;const y=ui.worldToLocal(dragPoint).y,steps=Math.trunc((y-drag.startY)/.1),maxRow=Math.max(0,Math.ceil(filteredCards().length/8)-2),next=Math.max(0,Math.min(maxRow,drag.startRow+steps));if(next!==row){row=next;drag.moved=true;message=`Coleção · posição ${row+1} de ${maxRow+1}.`;render();}return true;}
 function pointerEnd(source){if(!drag||drag.source!==source)return false;const finished=drag;drag=null;if(!finished.moved&&finished.id.startsWith('card-'))activate(finished.id,finished.object);return true;}
 render();
 return {stage,controls,detail,activate,navigate,pointerStart,pointerMove,pointerEnd,isDragging:source=>drag?.source===source,show(){stage.visible=true;render();},hide(){drag=null;stage.visible=false;},alignFrom(source){stage.position.copy(source.position);stage.rotation.copy(source.rotation);stage.updateMatrixWorld(true);},setDecks(next){if(validateDecks(next).ok){decks=next.map(deck=>deck.slice());persist();render();}},get visible(){return stage.visible;},get page(){return row;},get detailKey(){return detailKey;},get filter(){return FILTERS[filterIndex].label;},getDecks:()=>decks.map(deck=>deck.slice())};
}
